title: Site

tabs:
  pages:
    label: Content
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - project
              - about
              - works
              - default
      - width: 1/2
        sections:
          fields:
            fields:
              copyright:
                label: Copyright Text
                type: text

  seo:
  seo: seo/site
