title: Site

tabs:
  pages:
    label: Content
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - home
              - project
              - about
              - works
              - contact
              - default
      - width: 1/2
        sections:
          fields:
            fields:
              copyright:
                label: Copyright Text
                type: text

  global:
    label: Global Settings
    icon: settings
    columns:
      - width: 1/2
        sections:
          branding:
            type: fields
            fields:
              favicon:
                label: Site Favicon
                type: files
                multiple: false
                layout: cards
                size: small
                help: "Upload a PNG or ICO file. If empty, no favicon is set."

              navigation:
                label: Site Navigation
                type: structure
                fields:
                  label:
                    label: Menu Label
                    type: text
                    width: 1/2
                  link_type:
                    label: Link Type
                    type: toggles
                    width: 1/2
                    active: false
                    options:
                      internal: Internal Page
                      external: External URL
                    default: internal
                  page:
                    label: Internal Page
                    type: pages
                    max: 1
                    when:
                      link_type: internal
                  url:
                    label: External URL
                    type: url
                    when:
                      link_type: external

  seo: seo/site
